// @ts-check

const sidebars = {
  mainSidebar: [
    {
      type: 'doc',
      id: 'home',
      label: '🏠 首頁',
    },

    {
      type: 'category',
      label: '🎬 DaVinci Resolve',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'resolve',
        },
        
      ],
    },




    {
      type: 'category',
      label: '🦕 Docusaurus 筆記',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'Docusaurus',
        },
      ],
    },
  ],
};

export default sidebars;
