// @ts-check

const sidebars = {
  mainSidebar: [
    {
      type: 'doc',
      id: 'home',
      label: '🏠 首頁',
    },

    {
      type: 'category',
      label: '🎬 DaVinci Resolve 教學區',
      items: [
        {
          type: 'autogenerated',
          dirName: 'resolve',
        },
      ],
    },

    {
      type: 'category',
      label: '🎹 Finale 教學區',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Finale',
        },
      ],
    },

    {
      type: 'category',
      label: '🦕 Docusaurus 筆記區',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Docusaurus',
        },
      ],
    },
  ],
};

module.exports = sidebars;